apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: 'mitchkuijpers/authentication:latest'
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081