apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    name: authentication
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: authentication
  type: LoadBalancer